server:
  port: 8080

spring:
  application:
    name: gateway-service

  # Config Server Connection (Bootstrap Configuration)
  config:
    import: optional:configserver:http://localhost:8888/config-server/api/v1/config
    # Note: Using 'optional:' allows service to start even if Config Server is unavailable


# JWT Configuration
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
